plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/davidmarsh/Desktop/LiFi NYC/_Utilities/Websites/logan-loans-netlify"
publishOrigin = "default"
base = "/Users/davidmarsh/Desktop/LiFi NYC/_Utilities/Websites/logan-loans-netlify"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]